### ISSUE TITLE
initializeApp from a firebase function

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/firebase-admin-interop#1]
I wanted to use directly the firebase config from a firebase function to avoid to manually extract the various fields as done in JS here: https://firebase.google.com/docs/functions/get-started#import_the_required_modules_and_initialize

Unfortunately initializeApp does not take an AppOptions parameter. that could allow to do simply

    App app = firebaseAdmin.initializeApp(firebaseFunctions.config.firebase);

without having to worry which are the required fields (databaseURL, credential...). I forked it and created this simple change here: https://github.com/tekartik/firebase-admin-interop/commit/4b90ad33f1ec1d7a59f0cfec53e776e2b85994a5
I was able to use the admin feature directly from my cloud fonctions

However it is a breaking change. Let me know if you prefer to keep as is and what would be the way to initialize from a firebaseFunctions config or if you would accept a PR.

**Comment by pulyaevskiy** [comment]
Hi @alextekartik !

Sorry for late response. Feel free to submit a PR. Overall changes in your commit look good to me.

In general I'm trying to completely hide JS bindings from public API of the library but it seems like the only option in this case. So go ahead. 👍 

P.S.: I'll be traveling for next couple days and can be slow to respond.

**Comment by alextekartik** [comment]
I like the idea of hiding JS bindings too. That would mean wrapping many JS object though; i guess it could be done later

**Comment by pulyaevskiy** [comment]
New version is on Pub:
https://pub.dartlang.org/packages/firebase_admin_interop/versions/0.1.0-beta.4

Thanks again!
