### ISSUE TITLE
bug: FormatException with document.updateTime

### ISSUE THREAD

**Issue by asaarnak** [pulyaevskiy/firebase-admin-interop#19]
`FormatException: Invalid date format 2018-06-10T20:26:58.623519000Z`
`package:firebase_admin_interop/src/firestore.dart 307:39`
`DateTime get updateTime => DateTime.parse(nativeInstance.updateTime);`

**Comment by pulyaevskiy** [comment]
I've pushed a fix for this in #20.

In short, neither Dart's `DateTime` nor JS `Date` are able to properly handle this nanosecond precision date string so I had to change the type of `updateTime` to `String`. This value should really be treated as opaque when passed to any transaction in a precondition.
