### ISSUE TITLE
type (QueryDocumentSnapshot) => DocumentSnapshot' is not a subtype of type '(dynamic) => DocumentSnapshot'

### ISSUE THREAD

**Issue by grundid** [pulyaevskiy/firebase-admin-interop#22]
When calling the documents function on a QuerySnapshot I see the following exception:

```
TypeError: Closure 'QuerySnapshot_documents_closure': type '(QueryDocumentSnapshot) => DocumentSnapshot' is not a subtype of type '(dynamic) => DocumentSnapshot'
    at Object.wrapException 
    at Object.functionTypeCheck
    at Interceptor.map$1$1
    at Object.J.map$1$1$ax 
    at QuerySnapshot.get$documents 
    at index.dart.js
```

This was working a few days back.
My Dart version is:
Dart VM version: 2.0.0-dev.67.0 (Tue Jul 3 18:17:07 2018 +0200) on "macos_x64"

**Comment by pulyaevskiy** [comment]
Thanks for reporting! Looks like Dart is getting stronger with every new build.

I'll have some time today to look into this.

**Comment by grundid** [comment]
Thanks for looking into this.
I also see a problem with the body parser:

```
TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<String>'
```

This happens when I have a JSON Array with Strings in my request.

```json
{
 "data": ["element1"] 
}
```

**Comment by pulyaevskiy** [comment]
> This happens when I have a JSON Array with Strings in my request.

Will check it out as well. If you can provide an example code snippet, it would be easier for me to track down.

**Comment by pulyaevskiy** [comment]
See #23 for fixes.

**Comment by pulyaevskiy** [comment]
@grundid I've just published new version of admin interop package which fixes original issue.

I couldn't reproduce your error with JSArray, please file a separate bug preferably with an example, it'd help a lot in getting this fixed quicker.

**Comment by lukgutierrez** [comment]
hello
