### ISSUE TITLE
Add methods to the Reference / Query class to match Javascript docs 

### ISSUE THREAD

**Issue by TonyDowney** [pulyaevskiy/firebase-admin-interop#5]
List of operations here:
https://firebase.google.com/docs/reference/js/firebase.database.Reference

If I'm putting together a wishlist: orderByChild, startAt / endAt / equalTo, isEqual, limitToFirst / limitToLast, update.

**Comment by pulyaevskiy** [comment]
Thanks for taking time to submit this issue! I should actually have some time today to work on this. Stay tuned.

**Comment by pulyaevskiy** [comment]
1.0.0-dev.6.0 is now on Pub:
https://pub.dartlang.org/packages/firebase_admin_interop/versions/1.0.0-dev.6.0#-changelog-tab-

Should have all methods you mentioned.

Only `Query.off`, `Query.on` and `Reference.transaction` are missing, I think. Feel free to submit a separate issue if any of those become critical (and I don't get to them sooner :-) ).
