### ISSUE TITLE
firestore: missing select, offset; startAt/endAt/endAt/endBefore not working; FieldValue not exported

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/firebase-admin-interop#9]
I was playing again with your great wrapper. There were some missing features, and some not working so I took the liberty to create a pull request that you can use (or not!).
https://github.com/pulyaevskiy/firebase-admin-interop/pull/8

the unit tests failed for 2 reasons: Missing the env variables and some tests depends on some existing data.
As a side note, now that initializeApp can use a GOOGLE_CLOUD_PROJECT env variable, you can maybe remove the trick you used in test/setup.dart to set the firebase project
thanks!

**Comment by pulyaevskiy** [comment]
I've published `1.0.0-dev.10.0` with your changes from #8 .

> you can maybe remove the trick you used in test/setup.dart to set the firebase project

Not sure I fully understand what you mean here.  Do you mean to replace 4 env vars with a single `GOOGLE_CLOUD_PROJECT` var?

**Comment by alextekartik** [comment]
My bad, I thought I was able to use FIREBASE_CONFIG et GOOGLE_CLOUD_PROJECT before running in node in my own testing but actually it was using some global firebase environment

**Comment by pulyaevskiy** [comment]
Alright, I’ll close this than. But if you find other ways to reduce setup boilerplate feel free to open another issue!

**Comment by alextekartik** [comment]
@pulyaevskiy BTW, I confirm that we can we can use a single env variable in the following form (single line only though):

    export FIREBASE_CONFIG='{"apiKey": "xxx","authDomain": "xxx","databaseURL": "xxx","projectId": "xxx","storageBucket": "xxx","messagingSenderId": "xxx"}'

By doing so, no need to set any parameter when calling initializeApp for example

**Comment by pulyaevskiy** [comment]
Great, thanks! Would definitely need to upgrade to this some time soon. I've created #21 to track this.
